sudo: false
language: node_js
env:
  global:
    - PUBLIC_PATH = '/ptspIus.tv/'
node_js:
  - 10
cache: npm
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: dist